### ISSUE TITLE
Unable to select cql date type

### ISSUE THREAD

**Issue by ByEmke** [anguenot/pyspark-cassandra#21]
using CQL
```
CREATE TABLE temp (id int PRIMARY KEY , date date);
INSERT INTO temp (id, date) VALUES (2, '2017-12-01');
INSERT INTO temp (id, date) VALUES (3, '2017-12-02');
INSERT INTO temp (id, date) VALUES (4, '2017-12-03');
INSERT INTO temp (id, date) VALUES (5, '2017-12-04');
INSERT INTO temp (id, date) VALUES (6, '2017-12-05');
INSERT INTO temp (id, date) VALUES (7, '2017-12-06');
INSERT INTO temp (id, date) VALUES (8, '2017-12-04');
```

In pyspark using `pyspark --packages anguenot/pyspark-cassandra:0.6.0`
```
d = sc.cassandraTable('mykeyspace', 'tmp') \
  .select('id', 'date') \
  .where('date=?', '2017-12-01') \
  .collect()
```

Crashes with a long error, here's head of it
```
17/12/12 19:21:38 ERROR Executor: Exception in task 7.0 in stage 1.0 (TID 16)
net.razorvine.pickle.PickleException: couldn't introspect javabean: java.lang.IllegalArgumentException: wrong number of arguments
        at net.razorvine.pickle.Pickler.put_javabean(Pickler.java:727)
        at net.razorvine.pickle.Pickler.dispatch(Pickler.java:328)
        at net.razorvine.pickle.Pickler.save(Pickler.java:141)
```

I also noticed `date` type does not appear in the list of CQL types in the readme, does that mean it is not supported ?

**Comment by anguenot** [comment]
Hey @ByEmke, 

Thanks for the detailed bug report.

Mind testing out version 0.7.0 I released yesterday?

If you get the same issue, let me know and I will take a look at this and fix it.

Thanks.

   J.

**Comment by ByEmke** [comment]
Hey @anguenot , just tested the new release and it still crashes with the same error

**Comment by sathiyarajanm** [comment]
I have tested it and it is working as expected.
pyspark --packages anguenot/pyspark-cassandra:0.7.0

df = sql_context.read.format('org.apache.spark.sql.cassandra').options(table="temp", keyspace="mykeyspace").load()

df.select('id','date').where(df.date=='2017-12-01').show()
+---+----------+                                                                
| id  |          date|
+---+----------+
| 2 |2017-12-01|
+---+----------+

@ByEmke : validate it and let us know.

@anguenot : we can close this issue, since working as expected.

**Comment by anguenot** [comment]
Fix contributed by @dalonso82  and merged today. Thanks!
